### ISSUE TITLE
Broken trees

### ISSUE THREAD

**Issue by 00c** [Splizard/minetest-mod-snow#27]
Leaves from snow mod  do not decay with recent mt_game server 0.4.16 stable

**Comment by HybridDog** [comment]
It should be fixed now.
I did not add the decorated needles. Should they also decay or stay after digging the trunk?

**Comment by 00c** [comment]
Can stay. Thanks for fix

**Comment by 00c** [comment]
snow:leaves do not decay when trunk is removed

**Comment by HybridDog** [comment]
I made a fix but couldn't test it. You don't experience trees without trunks, do you?
![_compressed_screenshot_20171216_154031 png_](https://user-images.githubusercontent.com/3192173/34071600-8855c374-e278-11e7-84b8-1038ef175b43.jpg)

**Comment by 00c** [comment]
bug still exist, Pine trees work as they should, snow:leaves do not decay when trunk is removed.

**Comment by HybridDog** [comment]
Thanks, now it should be fixed.

**Comment by 00c** [comment]
Fixed

**Comment by 00c** [comment]
Leaves from default trees do not decay. I suspect this fix cause it.
When disabling snow mod default tree leaves decay fine. [issue](https://github.com/minetest/minetest_game/issues/2070)

**Comment by paramat** [comment]
See https://github.com/Splizard/minetest-mod-snow/commit/0dcf9b5f0e2a06e9d01c3ba52285d82a6bf341ac#commitcomment-27959002

**Comment by Splizard** [comment]
Fixed
